### ISSUE TITLE
Create TrafficStats api endpoint

### ISSUE THREAD

**Issue by pgicking** [PSU-Capstone-2014-B/routelandia-server#10]
Create an api endpoint /api/TrafficStats/ to allow the client to send the server two stationIDs that the server can do traffic statistics over. 

The two points should be stationIDs apart of the same highway, and the server will respond with relevant  traffic statistics. However until the relevant traffic statistics are decided, returning a json object of nulls, blanks or gibberish will have to do for now. 

In the future the endpoint will have to support a list of tuples for when the front end team is able to split highways into segments.

**Comment by joshproehl** [comment]
@pgicking Can we consider this one closed, since it's been created? (We might need to create further stories for the changes that will need to be made to it....)

Also, can we document some of what we know/decided about what statistics are in #18? (I wasn't at that meeting, but I'm happy to fill out the story from your notes if you like)

**Comment by pgicking** [comment]
Yea lets just close it
