### ISSUE TITLE
Get stationID from coordinates

### ISSUE THREAD

**Issue by pgicking** [PSU-Capstone-2014-B/routelandia-server#31]
I took a shot at this in this commit
1ccddafa4460f014cbb799a6a179de34003b5641

I was able to separate and convert the coordinates from the JSON string sent to the backend but could not figure out how to iterate through the geojson_raw and compare to see if they're the same.

**Comment by joshproehl** [comment]
@pgicking We shouldn't be iterating through the decoded geojson to compare. Since the client decided to give us points "somewhere nearby", we'll never actually get a match.

We need to be using something like (but not necessarily exactly) http://postgis.net/docs/ST_ClosestPoint.html to let PostGis take the point that the client gives back to us, and find the nearest segment_raw in the stations table.  (I think we're going to want to play around with this by manually entering coordinates into queries in the postgres command line before we start trying to build the queries in the PHP.)

In addition, just to complicate things, we're going to have to figure out which direction the user is trying to go. If they tap directly between the two lanes of the freeway the "nearest point" might be closer to the southbound lane, but if the end point is the north of start point, we'll have to use the highway that goes the other direction, if that makes sense...

I *think* the easiest thing to do here is to get the nearest station, but realize that we may also need it's opposite station, which we can get from opposite_stationid.

**Comment by pgicking** [comment]
I completely forgot about that bit. 

So since we're getting in decoded lat/long strings, but the server holds encoded strings, how is the connection made? Do we have to encode the coords and ship them off?

**Comment by joshproehl** [comment]
probably going to be some other postgis functions that will do the conversion from a string lat/lng to it's internal representation. ("pointFromString" or something like that?) 

Like I said, I'd play around with the postgres console to see if you can get something working with lat/lng's that you type in manually first, as a proof of concept.

**Comment by pgicking** [comment]
```SQL
SELECT ST_AsText(ST_ClosestPoint(pt,line)) AS cp_pt_line, 
	ST_AsText(ST_ClosestPoint(line,pt)) As cp_line_pt,
	foo.stationid as stationid
FROM (SELECT 'POINT(100 100)'::geometry As pt, 
		bar.segment_raw::geometry As line,
        bar.stationid
		FROM (SELECT ST_AsText(segment_raw) as segment_raw, stationid FROM stations As pt2) As bar
	) As foo;
```

This is what I have so far, but it compares against all of the linestrings of every stations, which is a problem since we only want one. Im not sure how to solve this problem seeing as the coordinates we're given wont be able to give us any information to narrow the query down to only certain line strings.

**Comment by joshproehl** [comment]
```sql
SELECT *
  FROM stations
  WHERE ST_Distance(ST_Transform(ST_GeomFromText('POINT(-122.78281856328249 45.44620177127501)', 4326), 3857), segment_raw) <= 500;
```

Seems to work!

**Comment by pgicking** [comment]
donerino, closing
